import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import { $ } from 'bun';

const projectRoot = path.resolve(import.meta.dirname, '..');
const distDir = path.join(projectRoot, 'dist');
const frontendDir = path.join(projectRoot, 'frontend');
const frontendDistDir = path.join(frontendDir, 'dist');

const isWindows = process.platform === 'win32';
const outputName = isWindows ? 'sqlview.exe' : 'sqlview';
const outputPath = path.join(distDir, outputName);
const installDir = path.join(os.homedir(), 'bin');
const installPath = path.join(installDir, outputName);

const embeddedAssetsPath = path.join(projectRoot, 'src', 'embedded-assets.js');

// 1. Build frontend
if (!fs.existsSync(path.join(frontendDir, 'package.json'))) {
  fail('Frontend project not found. Expected at: ' + frontendDir);
}

console.log('Building frontend...');
await $`cd ${frontendDir} && bun run build`;

if (!fs.existsSync(path.join(frontendDistDir, 'index.html'))) {
  fail('Frontend build failed: dist/index.html not found');
}

// 2. Generate embedded assets module
console.log('Generating embedded assets...');
const assets = collectFrontendAssets(frontendDistDir, frontendDistDir);
const assetCount = Object.keys(assets).length;
generateEmbeddedAssetsModule(assets, embeddedAssetsPath);
console.log(`Embedded ${assetCount} frontend assets.`);

// 3. Clean and prepare dist
fs.rmSync(distDir, { recursive: true, force: true });
fs.mkdirSync(distDir, { recursive: true });

// 4. Compile standalone binary
console.log('Compiling standalone binary...');
await $`bun build ${path.join(projectRoot, 'src', 'server.js')} --compile --minify --outfile ${outputPath}`;

// 5. Install to ~/bin
fs.mkdirSync(installDir, { recursive: true });
fs.copyFileSync(outputPath, installPath);
if (!isWindows) {
  fs.chmodSync(installPath, 0o755);
}

// 6. Clean up generated file
safeUnlink(embeddedAssetsPath);

console.log([
  'Build completed.',
  `Output: ${outputPath}`,
  `Installed: ${installPath}`,
  `Platform: ${os.platform()} ${os.arch()}`
].join('\n'));

function collectFrontendAssets(baseDir: string, currentDir: string): Record<string, string> {
  const result: Record<string, string> = {};
  for (const entry of fs.readdirSync(currentDir, { withFileTypes: true })) {
    const fullPath = path.join(currentDir, entry.name);
    if (entry.isDirectory()) {
      Object.assign(result, collectFrontendAssets(baseDir, fullPath));
    } else if (entry.isFile()) {
      const relative = path.relative(baseDir, fullPath).split(path.sep).join('/');
      result[relative] = fullPath;
    }
  }
  return result;
}

function generateEmbeddedAssetsModule(assets: Record<string, string>, outputPath: string) {
  const entries: string[] = [];
  for (const [relativePath, absolutePath] of Object.entries(assets)) {
    const content = fs.readFileSync(absolutePath);
    const base64 = content.toString('base64');
    const escaped = JSON.stringify(relativePath);
    entries.push(`  [${escaped}, Uint8Array.from(atob(${JSON.stringify(base64)}), c => c.charCodeAt(0))]`);
  }

  const code = [
    '// Auto-generated by scripts/build.ts — do not edit',
    `export const assets = new Map([`,
    entries.join(',\n'),
    `]);`,
    ''
  ].join('\n');

  fs.writeFileSync(outputPath, code, 'utf8');
}

function safeUnlink(targetPath: string) {
  try {
    fs.unlinkSync(targetPath);
  } catch {
    // Ignore cleanup failures
  }
}

function fail(message: string): never {
  process.stderr.write(`build error: ${message}\n`);
  process.exit(1);
}
